# Generated by Django 3.2 on 2021-04-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipoCliente',
            field=models.CharField(choices=[('CLIENTE', 'CLIENTE'), ('SUJETO RETENIDO', 'SUJETO RETENIDO'), ('DESTINATARIO', 'DESTINATARIO')], default='CLIENTE', max_length=50, verbose_name='Tipo Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipoIdentificacion',
            field=models.CharField(choices=[('CEDULA', 'CEDULA'), ('RUC', 'RUC'), ('PASAPORTE', 'PASAPORTE'), ('IDENTIFICACION DEL EXTERIOR', 'IDENTIFICACION DEL EXTERIOR')], default='CEDULA', max_length=50, verbose_name='Tipo Identificacón'),
        ),
    ]
